// Generated by LiveScript 1.6.0
(function(){
  var reg, binapi, com, printE, l, z, j, fail, F6, compute, out, E;
  reg = require("../dist/registry");
  binapi = require("../dist/main");
  com = reg.com, printE = reg.printE;
  l = com.l, z = com.z, j = com.j;
  fail = reg.printE.fail("test/test1.js");
  F6 = function(path, args, state){
    var number;
    number = args[0];
    switch (path.length) {
    case 0:
      return binapi(F6, number);
    case 1:
      switch (path[0]) {
      case "add":
        return binapi(F6, state + number);
      case "multiply":
        return binapi(F6, state * number);
      case "ret":
        return state;
      default:
        return fail(6);
      }
    default:
      return fail(6);
    }
  };
  try {
    compute = binapi(F6);
    out = compute(5).add(5).multiply(10).ret();
    if (!(out === 100)) {
      fail(7);
    }
  } catch (e$) {
    E = e$;
    l(E);
    fail(7);
  }
}).call(this);
