// Generated by LiveScript 1.6.0
(function(){
  var com, l, z, binapi, util, reg, fail, uic, Empty, Empty1, P, K, proxList, list, subtract, sub;
  com = require("../dist/common");
  l = com.l, z = com.z;
  binapi = require("../dist/main");
  util = require('util');
  reg = require("../dist/registry");
  fail = reg.printE.fail("test/test.js");
  uic = util.inspect.custom;
  Empty = function(obs){
    return obs;
  };
  Empty1 = function(obs){
    return obs;
  };
  Empty1[uic] = function(){
    return this;
  };
  P = binapi.obj(Empty);
  K = P.flip.callback();
  if (!(K.flip || K.callback)) {
    fail(1);
  }
  proxList = binapi.list(Empty);
  list = proxList.flip.callback();
  if (!(list[0] === 'flip' || list[1] === 'callback')) {
    fail(2);
  }
  subtract = function(flags, args){
    var a, b, temporary, output;
    a = args[0], b = args[1];
    if (flags.flip) {
      temporary = a;
      a = b;
      b = temporary;
    }
    output = a - b;
    if (flags.abs) {
      return Math.abs(output);
    }
    return output;
  };
  sub = binapi.obj(subtract);
  if (!(sub(10, 5) === 5)) {
    fail(4);
  }
  if (!(sub.flip.subtract(10, 5) === -5)) {
    fail(5);
  }
  if (!(sub.flip.abs(10, 5) === 5)) {
    fail(6);
  }
}).call(this);
