// Generated by LiveScript 1.6.0
var reg, binapi, com, printE, l, z, fail, main, getter, log, test, tsf;
reg = require("../dist/registry");
binapi = require("../dist/main");
com = reg.com, printE = reg.printE;
l = com.l, z = com.z;
fail = reg.printE.fail("test/test2.js");
main = function(){};
getter = function(state, key){
  return state.concat(key);
};
log = function(state){
  var chain;
  chain = state.join(' | ');
  return "( " + chain + " )";
};
test = binapi(main, getter, [], log);
tsf = test.sync.flip;