// Generated by LiveScript 1.6.0
(function(){
  var reg, binapi, com, printE, l, z, fail;
  reg = require("../dist/registry");
  binapi = require("../dist/main");
  com = reg.com, printE = reg.printE;
  l = com.l, z = com.z;
  fail = reg.printE.fail("test/test2.js");
}).call(this);
