name: binapi
author: sourcevault
email: joykrishnamondal@gmail.com
homepage: https://github.com/sourcevault/binapi#readme.md
license: BSD-3-Clause
description: binary api
repository: https://github.com/sourcevault/binapi.git
version: 0.1.01
main: dist/main.js
scripts:
  "test": "make travis"
dependencies:
  ramda: "0.26.1"
keywords:
  - ES6 Proxy
  - functional
  - immutable
  - livescript
  - simple
